# Generated by Django 6.0.6 on 2026-06-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prodcuto",
            new_name="Producto",
        ),
    ]
