# Generated by Django 6.0.6 on 2026-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoPremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("precio", models.IntegerField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="premium/"),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
